version: "3.8"
services:
  api:
    build: .
    profiles: ["api"]
    command: npm run start
    ports:
      - "5000:5000"
    environment:
      RABBIT_URL: amqp://<RABBITMQ_IP>:5672
      REDIS_URL: redis://<REDIS_IP>:6379
    depends_on:
      - rabbitmq
      - redis

  worker:
    build: .
    profiles: ["worker"]
    command: npm run worker
    environment:
      RABBIT_URL: amqp://<RABBITMQ_IP>:5672
      REDIS_URL: redis://<REDIS_IP>:6379
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    profiles: ["rabbitmq"]
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    profiles: ["redis"]
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander
    profiles: ["redisui"]
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: |
        local:<REDIS_IP>:6379
